@OrderCore.Api_HostAddress = http://localhost:5282

POST {{OrderCore.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "userName": "admin",
  "email": "admin@email.com",
  "password": "Admin123!",
  "role": "Admin"
}

###

POST {{OrderCore.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userNameOrEmail": "admin",
  "password": "Admin123!"
}

###

GET {{OrderCore.Api_HostAddress}}/api/products
Authorization: Bearer {{accessToken}}
Accept: application/json
###
